# Generated by Django 4.2.18 on 2025-01-19 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vps',
            options={'ordering': ('uid',), 'verbose_name': 'Сервер', 'verbose_name_plural': 'Серверы'},
        ),
        migrations.AlterField(
            model_name='vps',
            name='cpu',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Не менее одного ядра!'), django.core.validators.MaxValueValidator(10000, message='Превышено максимальное количество ядер!')], verbose_name='Количество процессорных ядер'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='hdd',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(128, message='Не менее 128 гигабайт!'), django.core.validators.MaxValueValidator(2048, message='Не более 2048 гигабайт!')], verbose_name='Объем дискового пространства'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ram',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1024, message='Не менее 1 гигабайта!'), django.core.validators.MaxValueValidator(65536, message='Не более 64 гигабайт!')], verbose_name='Объем оперативной памяти'),
        ),
    ]
